### ISSUE TITLE
Error when retrieving workouts

### ISSUE THREAD

**Issue by jestarr** [bweiher/pelotonR#11]
I'm getting an error when I try to retrieve my workouts:
``` r
library(pelotonR)
peloton_auth()
#> [1] "Logged in"

# get data about yourself
me <- get_my_info() # peloton_api("api/me")
user_id <- me$id

# get a list of your workouts
workouts <- get_all_workouts(user_id) # peloton_api("api/user_id/workouts")
#> Error: Can't combine `..1$v2_total_video_watch_time_seconds` <integer> and `..18$v2_total_video_watch_time_seconds` <character>.
```

**Comment by CDittmeier** [comment]
Hey @jestarr - I had the same issue. It occurred after trying to retrieve workout data after a recent ride. I temporarily resolved it by creating a second get_all_workouts function that excludes the first ride

`get_all_workouts2 <- function(userid = Sys.getenv("PELOTON_USERID"), num_workouts = 50, joins = "") {
  if (userid == "") stop("Provide a userid or set an environmental variable `PELOTON_USERID`", call. = FALSE)
  if (length(joins) > 1 || !is.character(joins)) stop("Provide joins as a length one character vector", call. = FALSE)
  
  # see if joins is provided, if so, append to request
  if (joins != "") joins <- glue::glue("joins={joins}")
  
  workouts <- peloton_api(glue::glue("/api/user/{userid}/workouts?{joins}&limit={num_workouts}&page=0"))
  n_workouts <- length(workouts$content$data)
  
  if (n_workouts > 0) {
    workouts <- purrr::map_df(2:n_workouts, ~ parse_list_to_df(workouts$content$data[[.]]))
    
    # IF JOIN PARAM is specified, get data out for ride list and add it to that row
    if (joins != "") {
      rides <- purrr::map_df(2:n_workouts, function(x) {
        tmp_ride <- parse_list_to_df(workouts$ride[[x]])
        stats::setNames(tmp_ride, paste0("ride_", colnames(tmp_ride)))
      })
      
      dplyr::left_join(dplyr::mutate(workouts, rn = dplyr::row_number()),
                       dplyr::mutate(rides, rn = dplyr::row_number()),
                       by  = "rn"
      ) %>%
        dplyr::select(-rn)
    } else {
      workouts
    }
  }
}`

I'm not sure if this is advisable or if the row numbers are kept consistent, but I wanted to start visualizing the data and didn't feel like waiting for the original get_all_workouts() to work. Also want to add for @bweiher that running `get_workouts_data(workout_ids)` is returning an error as well:

` Error: Can't combine `..1$achievement_templates` <character> and `..3$achievement_templates` <list>.`

**Comment by bweiher** [comment]
thanks @jestarr  -- I just issued a PR I think fixes this. let me know if it doesn't resolve. thanks!
